version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
workflows:
  build-deploy:
    jobs:
      - build-native-client
      - build-web-client
      - build-server
      - deploy-web-client:
          requires:
            - build-web-client
          filters:
            branches:
              only:
                - main
      - deploy-server:
          requires: 
            - build-server
          filters:
            branches:
              only:
                - main
            
jobs:
  build-native-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: native-client/node_modules
          app-dir: native-client
      - run:
          command: npm run format
          name: Check for Formatting Errors
          working_directory: native-client
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: native-client
      - run:
          command: npm test
          name: Run JavaScript Tests
          working_directory: native-client
      - persist_to_workspace:
          root: ./
          paths:
            - native-client/node_modules
  build-web-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: native-client/node_modules
          app-dir: native-client
      - run:
          command: npm run format
          name: Check for Formatting Errors
          working_directory: native-client
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: native-client
      - run:
          command: npm test
          name: Run Tests
          working_directory: native-client
      - persist_to_workspace:
          root: ./
          paths:
            - native-client/node_modules
  build-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: server/node_modules
          app-dir: server
      - run:
          command: npm run formatci
          name: Check for Formatting Errors
          working_directory: server
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: server
      - run:
          command: npm test
          name: Run Tests
          working_directory: server
      - run:
          command: npm run build
          name: Build JavaScript
          working_directory: server
      - persist_to_workspace:
          root: ./
          paths:
            - server/dist
            - server/node_modules
  deploy-web-client:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Netlify Deploy
          working_directory: client
          command: node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir prod
  deploy-server:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true

