# docker-compose.yml
version: '3'
services:
    app:
        build: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://devuser:pass@postgres:5432/postgres
            NODE_ENV: development
            PORT: 3000
        ports:
            - '3000:3000'
        command: npm run start:dev
        volumes:
            - .:/app/
            - /app/node_modules

    postgres:
        image: postgres:10.4
        ports:
            - '35432:5432'
        environment:
            POSTGRES_USER: devuser
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: postgres
